### PR TITLE
Add active/inactive prefixes

### PR DESCRIPTION
**Pull request by ana-kuznetsova**
Added more <np><al>

### CODE REVIEW

**Comment by ftyers** [comment]
@ana-kuznetsova should I merge this?

**Comment by ana-kuznetsova** [comment]
Is there any way to merge all the commits except `Add more proper names`? 
There are minor errors as some `<np><al>` that I added are normal grn words. I will fix it later.

**Comment by ftyers** [comment]
@sushain97 do you know an answer to @ana-kuznetsova's question?

**Comment by sushain97** [comment]
My apologies; I just saw this, @ftyers. When merging, use the squash button:

image

**Comment by ftyers** [comment]
Thanks @sushain97

**Pull request merged**
